### ISSUE TITLE
Bottom of Forum Doesn't Follow Dark Theme

### ISSUE THREAD

**Issue by friadev** [privacyguides/privacyguides.org#2792] opened 2024-10-28 21:50 UTC
### Bug description

If you scroll to the bottom of the page on the forum in dark mode, it will be white. It should match the theme of the rest of the page.

![Screenshot 2024-10-28 at 4 48 18 PM](https://github.com/user-attachments/assets/f18178d7-fa0f-423e-8d6d-84ebc175a663)

### Affected pages

https://discuss.privacyguides.net

### Browser

Safari

### Operating System

macOS

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment] 2024-10-28 22:02
Duplicate of https://github.com/privacyguides/discourse-brand/issues/1

**Closed by jonaharagon** 2024-10-28 22:02 UTC
Labels: t:bug, status:duplicate
