### ISSUE TITLE
Safari and Webkit isn't the only option anymore

### ISSUE THREAD

**Issue by minternational** [privacyguides/privacyguides.org#2627] opened 2024-06-29 10:31 UTC
### Affected page

https://www.privacyguides.org/en/mobile-browsers/#ios

### Description

Maybe it would be cool, to refresh this section. I am asking myself, if Brave Browser on iOS would be a better choice than Safari, since Apple opened not only the selection of the standard browser but also the choice of the Engine for each browser at least in the EU.

### Sources

https://www.theverge.com/2024/1/25/24050478/apple-ios-17-4-browser-engines-eu

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by redoomed1** [comment] 2024-06-29 13:53
This is a duplicate of the following thread on the [official forum](https://discuss.privacyguides.net/): [Mention iOS 17.4 non-WebKit browsers](https://discuss.privacyguides.net/t/mention-ios-17-4-non-webkit-browsers/16571).

**Closed** 2024-06-30 07:42 UTC
Labels: t:correction
