### ISSUE TITLE
Piped improvements

### ISSUE THREAD

**Issue by Lostname777** [privacyguides/privacyguides.org#1321] opened 2022-05-25 14:41 UTC
### Discussed in https://github.com/orgs/privacyguides/discussions/1302

<div type='discussions-op-text'>

<sup>Originally posted by **Lostname777** May 23, 2022</sup>
piped.kavin.rocks uses cloudflare cdn which can be a concern for some many users because of privacy policy of cloudfare. Please add some notice of changing piped instance to the one without cdn or with no cloudflare cdn.</div>

**Comment by jonaharagon** [comment] 2022-05-25 17:30
Duplicate of #1302

**Closed by jonaharagon** 2022-05-25 17:30 UTC
Labels: status:duplicate
