### ISSUE TITLE
Website Issue | Right side "overflow"

### ISSUE THREAD

**Issue by 1hiking** [privacyguides/privacyguides.org#837] opened 2022-04-01 21:40 UTC
## Description

On mobile devices, the left side will overflow, it seems to be caused by the buttons on the bottom.

Hopefully not an upstream issue so that it can be fixed :B

## Screenshots

![image](https://user-images.githubusercontent.com/73438877/161344858-09431b90-eaed-47ed-af12-30efc8514ac8.png)

**Comment by dngray** [comment] 2022-04-02 03:26
Hmm, I tried this on my phone and couldn't reproduce, could you provide steps to reproduce?

**Comment by jonaharagon** [comment] 2022-04-02 03:28
Fixed in #843

**Closed by jonaharagon** 2022-04-02 03:28 UTC
