### ISSUE TITLE
Yattee (YouTube Frontend)

### ISSUE THREAD

**Issue by holequantum** [privacyguides/privacyguides.org#1675] opened 2022-08-22 10:24 UTC
If this gets listed also https://github.com/privacyguides/privacyguides.org/discussions/457 should be pushed through. Basically same features for iOS and MacOS. Also uses Piped and SponsorBlock.

_Originally posted by @ph00lt0 in https://github.com/privacyguides/privacyguides.org/discussions/1594#discussioncomment-3445783_

**Comment by jonaharagon** [comment] 2022-08-22 23:35
Duplicate of #457.

**Closed by jonaharagon** 2022-08-22 23:35 UTC
Labels: status:duplicate
