### ISSUE TITLE
SimpleX Offers Desktop Apps

### ISSUE THREAD

**Issue by benmordecai** [privacyguides/privacyguides.org#2304] opened 2023-10-11 00:32 UTC
### Affected page

https://www.privacyguides.org/en/real-time-communication/#simplex-chat

### Description

Privacy Guides text states:

> Currently SimpleX Chat only provides a client for Android and iOS. Basic group chatting functionality, direct messaging, editing of messages and markdown are supported. E2EE Audio and Video calls are also supported.

The SimpleX website contains Linux, Mac, and Windows download links for desktop apps. It is worth noting that it is not currently possible to use the same profile in two devices. 

### Sources

https://simplex.chat/downloads/

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment] 2023-10-11 01:24
Thank you! This is already fixed in the next release. Duplicate of #2283

**Closed by jonaharagon** 2023-10-11 01:24 UTC
Labels: t:correction
