### ISSUE TITLE
Cypth Webmail Client

### ISSUE THREAD

**Issue by x0tester0x** [privacyguides/privacyguides.org#487] opened 2021-12-20 22:43 UTC
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/409

<div type='discussions-op-text'>

<sup>Originally posted by **x0tester0x** November 29, 2021</sup>
Can you add [Cypht](https://cypht.org/) to the Mail Clients?</div>

**Comment by jonaharagon** [comment] 2021-12-30 19:19
Duplicate of #409

**Closed by jonaharagon** 2021-12-30 19:19 UTC
