### ISSUE TITLE
Set up coordinated localisation effort with the help of LocalisationLab

### ISSUE THREAD

**Issue by Blac59** [privacyguides/privacyguides.org#493] opened 2021-12-22 23:15 UTC
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **freddy-m** May  7, 2021</sup>
[LocalisationLab](https://www.localizationlab.org/) makes "FLOSS technology accessible through collaboration with developers, organizations, end users, and communities in need. Our crowdsourced localization results in more accurate and timely translations and unlocks access to the internet for users all over the world". 

One of our moderators, @Trai-Dep, suggested that we use this - and given the ammount of translation requests that we've been getting as of late, I think it can only be a good idea.

Would be interested to hear you thoughts @blacklight447-ptio?</div>

**Comment by jonaharagon** [comment] 2021-12-30 19:20
Duplicate of #30

**Closed by jonaharagon** 2021-12-30 19:20 UTC
