### ISSUE TITLE
Improve Invidious logo contrast on dark mode

### ISSUE THREAD

**Issue by 1hiking** [privacyguides/privacyguides.org#398] opened 2021-11-28 21:19 UTC
## Description

The current logo of Invidious does not have a great contrast on dark mode. I have quickly found a SVG black+transparency version on the Invidious repo which imo looks better:

![image](https://user-images.githubusercontent.com/73438877/143786308-214733f7-6fb6-4abd-a8f9-3536fa9e7bfe.png)

[Here is the file](https://raw.githubusercontent.com/iv-org/invidious/edb37c95e1c9dbf1abf2647fcfcd1453c38124c1/assets/safari-pinned-tab.svg)

**URL of affected page:**
https://privacyguides.org/video-streaming/

**Comment by dngray** [comment] 2021-11-29 04:00
Duplicate of https://github.com/privacyguides/privacyguides.org/issues/401 this doesn't just effect the Invidious logo. We need to implement the code to use the `invidious-dark.svg` variant that is in the repo.

**Closed by dngray** 2021-11-29 04:00 UTC
