### ISSUE TITLE
controld free plan (no logs?)

### ISSUE THREAD

**Issue by ignoramous** [privacyguides/privacyguides.org#2497] opened 2024-04-06 17:51 UTC
### Affected page

https://www.privacyguides.org/en/dns/

### Description

PrivacyGuides today points out:
> Free [ControlD] resolvers listed on the homepage do not store this or any other data including but not limited to IP addresses, timestamps, or DNS queries themselves.

But from [this recent r/controld thread](https://archive.is/9EYHH) [^f], it looks like they do block "abusive IPs". Clarification is required on how they achieve this across all their servers,[^u] if they do not log *any* form of information on incoming requests? May be there's `[hash(IP, salt), integer-counter]` in their datastore somewhere, but that isn't "do not store this or any other data..." like posited on PrivacyGuides.

[^f]: IP bans are for X hours, and are per-IP. This usually means someone on your network sent a LOT of DNS queries, perhaps without realizing, or maliciously. As we've been under DDOS attack recently, the anti-abuse system is very trigger happy, especially with free resolvers. 
[^u]: Disclaimer: I run *rethinkdns*, a public DNS-over-HTTPS / DNS-over-TLS resolver that is "similar" to Free ControlD.

### Sources

https://archive.is/XH2sm#fn:3

https://archive.is/9EYHH / https://www.reddit.com/r/ControlD/comments/1bnoriq/my_ip_range_isp_is_banned_for_good_after_using/

### Before submitting

- [ ] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment] 2024-04-06 20:58
Could certainly ask them, but I'm not sure why you'd need historical data logs to block abusive IP ranges. Presumably if you're ControlD, and you're noticing lower performance or higher bandwidth usage from your servers, you can see where the traffic is coming from at that moment and block accordingly.

**Comment by ignoramous** [comment] 2024-04-06 21:57
> you can see where the traffic is coming from at that moment and block accordingly

Usually such abuse systems are automated and not manual, and the sophisticated ones are multi-region. Someone hints at the automation in that subreddit thread: "our anti-abuse system is trigger happy".

> historical data logs to block abusive IP ranges

That's not the point of this issue, which is specifically about PG claim that *ControlD Free* doesn't store *anything* at all.

> if you're ControlD, and you're noticing lower performance or higher bandwidth usage from your servers

It isn't clear if ControlD runs its own DDoS protection layer (they could be).

**Comment by jonaharagon** [comment] 2024-04-07 02:23
> doesn't store anything at all.

It is the point of this issue. I'm saying you haven't explained why this means they do store anything. The fact that they are automated does not necessarily change the process I outlined: The process could kick in based on # of requests made within a fixed window, for example.

Unless you are saying the fact that they stored an IP range to block as an iptables rule (or whatever) counts as them storing data for this purpose? The page does not literally mean ControlD does not possess any conceivable form of data. I could rattle off all sorts of _data_ they possess, their webservers possess the HTML data that makes up their homepage, their social media accounts possess the contents of their posts, etc. - It is not relevant to us.

In that case this issue would be a duplicate of #2484 (i.e. that the definition of logging on the page is imprecise) and that will be fixed anyways.

**Comment by jonaharagon** [comment] 2024-04-07 02:24
Or should we say that "store" implies "to disk"?

**Comment by ignoramous** [comment] 2024-04-07 02:48
>  I'm saying you haven't explained why this means they do store anything.

The burden to prove whatever it is they do can't be on me, surely? To put it bluntly, most other large public resolvers elaborate exactly what they store and why, incl for DDoS. The "no logs" resolvers recommended by PrivacyGuides however seem to be lacking in transparency in that regard?

> The process could kick in based on # of requests made within a fixed window, for example.

That's *load shedding* / *admission control*? DDoS prevention isn't limited to that (for example, some may meter ingress and egress bandwidth, number of queries as opposed to number of connections, handshake / connection failures, connection stalls, query type, query name, query frequency, time-to-live abuse, non-compliant stub clients, using IP hopping services and so on). I am not privy to what ControlD does, or how it defines DDoS, for that matter.

> duplicate of #2484 that the definition of logging on the page is imprecise

This issue *depends* on just what definition of "no logs" community settles on, yeah. Not necessarily a dupe? In fact, following up with ControlD might help decide what "no logs" should look like. Yegor, the founder, is pretty nice and approachable.

**Comment by jonaharagon** [comment] 2024-04-07 02:59
> The burden to prove whatever it is they do can't be on me, surely?

ControlD does [share](https://controld.com/privacy) what information they store though, you're the one refuting it, so it feels like something beyond speculation should be required...

**Comment by ignoramous** [comment] 2024-04-07 03:19
> ControlD does [share](https://controld.com/privacy) what information they store though, you're the one refuting it, so it feels like something beyond speculation should be required...

The policy (last updated 4 months ago) says the same thing as the PG page, that *ControlD Free* doesn't store IP addresses or timestamps or queries. Apparently these DDoS protections were put in place only recently according to the reddit thread. The only way to know *for sure* what they do is to ask them? If you think or strongly believe a counter or iptables is what they use and the fact that they haven't updated their privacy policy is proof of that, that *also* sounds reasonable.

**Comment by jonaharagon** [comment] 2024-04-07 07:27
I wonder if I can ping @yegors here to ask how they've implemented their DDoS protection with ControlD 👀 

Otherwise I'll email them :)

**Comment by jonaharagon** [comment] 2024-04-10 07:56
Duplicate of #2484

**Closed** 2024-04-10 13:37 UTC
Labels: c:question
